### ISSUE TITLE
Mod requests nonexistent file

### ISSUE THREAD

**Issue by ghost** [Geolykt/FastStar#1]
The current version when built version seems to request  a file that doesn't exist. I've tested it and [the 2024-07-12 commit(?)](https://github.com/Geolykt/FastStar/tree/2b898e28b8d14d381a75b00240194c96a33e75ad) when built doesn't have this problem. Here's stuff I got when I ran `java -cp launcher-micromixin-4.0.0-shaded.jar de.geolykt.starloader.launcher.CLILauncher` in a terminal that was at the Galimulator folder.

```
[main] [15:52:20.068] [INFO] de.geolykt.starloader.launcher.CLILauncher: Using prototypes from following sources:
[main] [15:52:20.069] [INFO] de.geolykt.starloader.launcher.CLILauncher: - StarloaderAPI v2.0.0-SNAPSHOT (loaded from [file:/home/nope/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Galimulator/mods/starloader-api-2.0.0-remapped.jar])
[main] [15:52:20.069] [INFO] de.geolykt.starloader.launcher.CLILauncher: - FAST v1.1.1 (loaded from [file:/home/nope/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Galimulator/mods/fast-asynchronous-starlane-triangulator-1.1.1.jar])
[main] [15:52:20.070] [INFO] de.geolykt.starloader.launcher.CLILauncher: - FastStar v2.2.0 (loaded from [file:/home/nope/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Galimulator/mods/faststar-2.2.0-remapped.jar])
[main] [15:52:20.071] [INFO] de.geolykt.starloader.Starloader: Java version: 21.0.4. JavaInterop J9: true
[ForkJoinPool.commonPool-worker-1] [15:52:21.052] [WARN] org.stianloader.picoresolve.MavenResolver: Unable to obtain the versions available for artifact 'it.unimi.dsi:fastutil-core'. It is likely that the relevant maven-metadata.xml file is missing. This may hamper resolution stability (especially when version ranges are being used) as the available versions will be guessed instead. See debug log output for the full relevant stacktrace.
[main] [15:52:22.459] [ERROR] de.geolykt.starloader.mod.ExtensionManager: Unable to fetch remote dependencies of extension FastStar v2.2.0.
java.lang.RuntimeException: Unable to fetch remote dependencies of extension FastStar, version 2.2.0
	at de.geolykt.starloader.mod.ExtensionManager.newClassLoader(ExtensionManager.java:423)
	at de.geolykt.starloader.mod.ExtensionManager.loadExtensions(ExtensionManager.java:135)
	at de.geolykt.starloader.Starloader.start(Starloader.java:46)
	at de.geolykt.starloader.Starloader.start(Starloader.java:80)
	at de.geolykt.starloader.launcher.CLILauncher.main(CLILauncher.java:103)
Caused by: java.util.concurrent.ExecutionException: org.stianloader.picoresolve.internal.MultiCompletableFuture$MultiCompletionException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at de.geolykt.starloader.mod.ExtensionManager.newClassLoader(ExtensionManager.java:420)
	... 4 more
Caused by: org.stianloader.picoresolve.internal.MultiCompletableFuture$MultiCompletionException
	at org.stianloader.picoresolve.internal.StronglyMultiCompletableFuture.sourceException(StronglyMultiCompletableFuture.java:78)
	at org.stianloader.picoresolve.internal.StronglyMultiCompletableFuture.lambda$new$1(StronglyMultiCompletableFuture.java:41)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at org.stianloader.picoresolve.internal.MultiCompletableFuture.sourceException(MultiCompletableFuture.java:68)
	at org.stianloader.picoresolve.internal.MultiCompletableFuture.lambda$new$0(MultiCompletableFuture.java:43)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at org.stianloader.picoresolve.internal.ConcurrencyUtil.lambda$schedule$0(ConcurrencyUtil.java:29)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: org.stianloader.picoresolve.internal.MultiCompletableFuture$MultiCompletionException
		... 13 more
		Suppressed: java.io.IOException: Query for https://stianloader.org/maven/it/unimi/dsi/fastutil-core/8.5.13/fastutil-core-8.5.13.pom returned with a response code of 404 (Not Found)
			at de.geolykt.starloader.util.MirroringURIMavenRepository.getResource0(MirroringURIMavenRepository.java:85)
			at de.geolykt.starloader.util.MirroringURIMavenRepository.lambda$getResource$0(MirroringURIMavenRepository.java:62)
			at org.stianloader.picoresolve.internal.ConcurrencyUtil.lambda$schedule$0(ConcurrencyUtil.java:27)
			... 6 more
		Suppressed: java.io.IOException: Query for https://stianloader.org/central-mirror/it/unimi/dsi/fastutil-core/8.5.13/fastutil-core-8.5.13.pom returned with a response code of 404 (Not Found)
			at de.geolykt.starloader.util.MirroringURIMavenRepository.getResource0(MirroringURIMavenRepository.java:85)
			at de.geolykt.starloader.util.MirroringURIMavenRepository.lambda$getResource$0(MirroringURIMavenRepository.java:62)
			at org.stianloader.picoresolve.internal.ConcurrencyUtil.lambda$schedule$0(ConcurrencyUtil.java:27)
```

**Comment by Geolykt** [comment]
Given that 2.2.0 is still indev, the dependencies have not been uploaded to the stianloader mirror yet. To work around this issue you need to configure SLL to bypass the mirror by adding `-Dorg.stianloader.sll.log.MIRROR_MAVEN_REQUESTS=true` to the jvm arguments.

With how you launch the game, that would equate to starting the game like follows:

```sh
java -Dorg.stianloader.sll.log.MIRROR_MAVEN_REQUESTS=true -cp launcher-micromixin-4.0.0-shaded.jar de.geolykt.starloader.launcher.CLILauncher
```

**Comment by ghost** [comment]
Thank you.
